### ISSUE TITLE
Diferença com a lib oficial do pagseguro

### ISSUE THREAD

**Issue by pedroviana** [claudiosanches/woocommerce-pagseguro#100]
Olá @claudiosanches !

Primeiramente gostaria de agradecer pela sua contribuição desse repositório.

Gostaria de entender que diferença tem esse plugin com o oficial do pagseguro: https://github.com/pagseguro/woocommerce

Poderia falar um pouco?

Uma coisa que não achei por aqui é a possibilidade de usar o módulo de pagamentos recorrentes, confere?

Obrigado!

**Comment by claudiosanches** [comment]
Diferença é que um eu fiz e o outro foi o PagSeguro que fez.
Eu não tive tempo livre ainda para implementar pagamentos recorrentes.
