### ISSUE TITLE
[DUVIDA] Limitar quantidade de parcelas - Checkout Transparente

### ISSUE THREAD

**Issue by jonnyso** [claudiosanches/woocommerce-pagseguro#102]
Olá,

Preciso limitar a quantidade disponível de parcelas de 12x para apenas 4x, pelo que entendi lendo outras perguntas a respeito, seria necessário editar o código do plugin. Tenho experiência em PHP e Javascript, mas sou iniciante em wordpress e não sei onde começar para fazer essa alteração. Poderiam me indicar por onde começar ?

**Comment by LFMAKER** [comment]
Conseguiu? Dei uma olhada no código do plugin porém sem ideia de onde começar

**Comment by jonnyso** [comment]
Consegui, queria criar um PR pra tornar isso configuravel mas não manjo de plugins do wordpress. De qualquer forma, é só alterar esse foreach no arquivo transparent-checkout.js:

![image](https://user-images.githubusercontent.com/30509290/56662708-fdb43600-667a-11e9-9b31-5005e70891a1.png)

Por exemplo, no meu caso eu queria apenas de 4x

`$.each(data.installments[brand].length > 4 && data.installments[brand].slice(0,4) || data.installments[brand], ...);`
