### ISSUE TITLE
WordPress (Woocomerce + Plugin Pagseguro), não atualiza o Status da compra

### ISSUE THREAD

**Issue by atmmoreira** [claudiosanches/woocommerce-pagseguro#109]
Olá Claudio, tudo bem?
Primeiramente, parabéns pela iniciativa de desenvolver o plug-in Pagseguro. 
**_Estou com o problema, seguinte:_** Quando o cliente paga o produto pelo pagseguro, o WordPress (Woocomerce + Plugin Pagseguro), não atualiza o Status do mesmo.

Como devo proceder para que o status deva ser atualizado automaticamente. Segui a risca, suas instruções e mesmo assim não atualiza o status.

OBS: Não sou desenvolvedor, rsss.

**Comment by claudiosanches** [comment]
Aqui tem todas as instruções de como resolver isso: https://github.com/claudiosanches/woocommerce-pagseguro#o-status-do-pedido-n%C3%A3o-%C3%A9-alterado-automaticamente
