### ISSUE TITLE
Sanbox localhost

### ISSUE THREAD

**Issue by marcelogarbin** [claudiosanches/woocommerce-pagseguro#121]
Olá, 
Gostaria de saber se é possível obter retorno do PagSeguro quando usado o plugin em ambiente localhost.
Se sim, como posso fazer isso?

 Obrigado

**Comment by Diegocndd** [comment]
@marcelogarbin, em geral você deve configurar sua máquina e realizar a integração com o PagSeguro para conseguir ter controle dos pagamentos em http://localhost:8080/pagseguro. Você pode usar uma API para auxiliar no desenvolvimento. Talvez esse [artigo ](https://medium.com/@bcostabatista/integrando-api-de-checkout-transparente-do-pagseguro-com-angular-e-nodejs-37126a62a02d)lhe ajude.

**Comment by marcelogarbin** [comment]
> @marcelogarbin, em geral você deve configurar sua máquina e realizar a integração com o PagSeguro para conseguir ter controle dos pagamentos em http://localhost:8080/pagseguro. Você pode usar uma API para auxiliar no desenvolvimento. Talvez esse [artigo ](https://medium.com/@bcostabatista/integrando-api-de-checkout-transparente-do-pagseguro-com-angular-e-nodejs-37126a62a02d)lhe ajude.

Obrigado vou conferir, de momento vou fechar essa issue.
