### ISSUE TITLE
Erros com cookies e dna.min.js

### ISSUE THREAD

**Issue by diegocgaona** [claudiosanches/woocommerce-pagseguro#131]
Olá,

No checkout da página (após clicar em finalizar compra no carrinho) estou tendo alguns erros com o PagSeguro:

Endereço: https://ateliecatorze.com/loja/

```
GET https://dna.uol.com.br/service/cookie?dnaReferer=https%3A%2F%2Fateliecatorze.com%2F&_=1604665471841 404 (Not Found)
e	@	dna.min.js:3
g	@	dna.min.js:3
h	@	dna.min.js:3
get	@	dna.min.js:3
serverRequest	@	dna.min.js:3
init	@	dna.min.js:6
(anonymous)	@	dna.min.js:6
setTimeout (async)		
(anonymous)	@	dna.min.js:6
f	@	dna.min.js:6
get	@	dna.min.js:6
t.getPersistedData	@	dna.min.js:6
e	@	dna.min.js:6
s	@	dna.min.js:6
(anonymous)	@	dna.min.js:7
o	@	dna.min.js:6
(anonymous)	@	dna.min.js:6
l	@	dna.min.js:6
(anonymous)	@	dna.min.js:7
(anonymous)	@	dna.min.js:6
setInterval (async)		
b.canRun	@	dna.min.js:6
run	@	dna.min.js:7
(anonymous)	@	dna.min.js:7
setTimeout (async)		
t.instantiate	@	dna.min.js:7
t.addClosure	@	dna.min.js:7
run	@	dna.min.js:7
(anonymous)	@	pagseguro.mediator.d….1604021034447.js:1
setTimeout (async)		
setDNA	@	pagseguro.mediator.d….1604021034447.js:1
(anonymous)	@	pagseguro.mediator.d….1604021034447.js:1
k	@	jquery-1.8.2.min.1604021034447.js:2
fireWith	@	jquery-1.8.2.min.1604021034447.js:2
ready	@	jquery-1.8.2.min.1604021034447.js:2
D	@	jquery-1.8.2.min.1604021034447.js:2
```

__________________________________________________________________________

```
GET https://dna.uol.com.br/service/etag?dnaReferer=https%3A%2F%2Fateliecatorze.com%2F 412 (Precondition Failed)
e @ dna.min.js:3
g @ dna.min.js:3
h @ dna.min.js:3
get @ dna.min.js:3
etagRequest @ dna.min.js:3
init @ dna.min.js:6
(anonymous) @ dna.min.js:6
setTimeout (async)
(anonymous) @ dna.min.js:6
f @ dna.min.js:6
get @ dna.min.js:6
t.getPersistedData @ dna.min.js:6
e @ dna.min.js:6
s @ dna.min.js:6
(anonymous) @ dna.min.js:7
o @ dna.min.js:6
(anonymous) @ dna.min.js:6
l @ dna.min.js:6
(anonymous) @ dna.min.js:7
(anonymous) @ dna.min.js:6
setInterval (async)
b.canRun @ dna.min.js:6
run @ dna.min.js:7
(anonymous) @ dna.min.js:7
setTimeout (async)
t.instantiate @ dna.min.js:7
t.addClosure @ dna.min.js:7
run @ dna.min.js:7
(anonymous) @ pagseguro.mediator.directpayment.dnaintegration.1604021034447.js:1
setTimeout (async)
setDNA @ pagseguro.mediator.directpayment.dnaintegration.1604021034447.js:1
(anonymous) @ pagseguro.mediator.directpayment.dnaintegration.1604021034447.js:1
k @ jquery-1.8.2.min.1604021034447.js:2
fireWith @ jquery-1.8.2.min.1604021034447.js:2
ready @ jquery-1.8.2.min.1604021034447.js:2
D @ jquery-1.8.2.min.1604021034447.js:2
```

________________________________________________________________________________

O que poderia causar isso? Poderia me ajudar?
Antes não havia esse erro, mas não sei desde quando acontece, notei nos últimos dias e não consegui resolver.
Aparentemente causa grande lentidão no processo.

Obrigado, Diego.

**Comment by rcnascimento** [comment]
@diegocgaona também observei umas requisições desconhecidas realizadas pelo meu website no momento em que a lib do checkout transparente era baixada do server do PagSeguro. São vários scripts de domínios diferentes, alguns deles disparando erros e adicionando uma grande sobrecarga de requisições ao processo.

Em contato com o PagSeguro fui informado que estas requisições são dependências da lib, e que elas são responsáveis por garantir algum grau de verificação de segurança para os pagamentos que usam esta integração (checkout transparente).

Portanto isso não é exatamente um bug, e menos ainda algo de responsabilidade deste plugin.

**Comment by diegocgaona** [comment]
@rcnascimento , obrigado pelo esclarecimento.

Entendo que pela sua explicação realmente não deve ser algo relacionado ao plugin.
Mas sinceramente, requisições com erro 404 não me parece ser realmente um "erro não intencional", acho bastante estranho uma verificação de segurança retornar erro e isso ser considerado comportamento normal por eles, parece que alguma das dependências está fazendo chamadas inválidas. Não sou especialista na área... então posso estar errado.

Obrigado mais uma vez, Diego.
