### ISSUE TITLE
É obrigatório incluir no checkout o país em que a transação é realizada

### ISSUE THREAD

**Issue by bruno-barros** [claudiosanches/woocommerce-pagseguro#43]
Notificação do PagSeguro.
+++
Devido à nova regulamentação da Bandeira Visa, informamos que é obrigatório incluir no checkout o país em que a transação é realizada.
Já implementamos esta atualização nos checkouts tipo padrão e lightbox. Como você utiliza o checkout transparente, a atualização precisa ser feita diretamente em seu site.
O prazo limite para a regularização é até 31/01/2017, sujeito à aplicação de multa pela bandeira caso haja o descumprimento.

Atenciosamente,
Equipe PagSeguro
+++

Alguém viu? Precisamo alterar alguma coisa no checkout transparente, ou o plugin já adiciona o pais por padrão?

Abs

**Comment by claudiosanches** [comment]
Sempre o pais é definido como "BRA", é o único valor que o PagSeguro consegue aceitar.
https://github.com/claudiosanches/woocommerce-pagseguro/blob/master/includes/class-wc-pagseguro-xml.php#L187

**Comment by claudiosanches** [comment]
E até agora na documentação parece que nada mudou.

**Comment by bruno-barros** [comment]
Ok. Obrigado.
