### ISSUE TITLE
Erro no número de telefone

### ISSUE THREAD

**Issue by pcolenbr** [claudiosanches/woocommerce-pagseguro#44]
Boa tarde,

Estou com um problema quando tento usar o checkout transparente no meu site.

Não importa qual número de telefone que eu coloque ele sempre me retorna: "PagSeguro: Por favor, digite um número de telefone válido com DDD. Exemplo: (11) 5555-5555."

Já tentei com diferentes DDD e com 8 ou 9 digitos, mas não consigo fazer funcionar.
Você sabe o que pode estar acontecendo?

[Formulário](https://postimg.org/image/d0ok5rzfr/)
[Erro](https://postimg.org/image/doxeopy5j/)

**Comment by claudiosanches** [comment]
Tem outros erros juntos, veja o log do plugin, talvez o problema seja a combinação de todos os erros juntos.
Mas telefone funciona sem nenhum problema, caso o contrário seria impossível usar este plugin que tem hoje milhares de usuários.

**Comment by iCristiano** [comment]
@claudiosanches tô tendo o mesmo problema com a validação do telefone... aparece o erro: "PagSeguro: Por favor, digite um número de telefone válido com DDD. Exemplo: (11) 5555-5555"

Acredito que o problema seja com os 9 dígitos...

**Comment by iCristiano** [comment]
Acho que descobri o problema... é que existem 3 campos de telefone do formulário:

Form Detalhes da Cobrança
1) Telefone (opcional)
2) Celular (opcional)

Form Checkout Transparente
3) Telefone do Portador

Como os 2 primeiros telefones aparecem como opcionais, as pessoas muitas vezes não os preenchem. Então, aparentava que o erro seria por conta do telefone do form do checkout. Mas o problema é que o Telefone (1) não estava sendo preenchido.

Sugestão: Ou realmente deixa esse campo como opcional ou, se for necessário mantê-lo obrigatório, que tire o "(opcional)" do label e coloque o asterisco.

Aproveito pra dizer que o campo "Bairro" tem o mesmo problema. Aparece como opcional mas, na verdade, é obrigatório.

Obrigado!

**Comment by eduardorl** [comment]
Olá!
Estou tendo o mesmo problema. Mudei o método de integração de Redirecionamento (funcionava perfeito e Telefone é **realmente** opcional) para checkout transparente e passei a ter esse problema.

@iCristiano você realizou alguma dessas soluções que você sugere?

**Comment by iCristiano** [comment]
@eduardorl a sugestão foi para os desenvolvedores do plugin...

**Comment by eduardorl** [comment]
@iCristiano já encontrei a solução (código) nas respostas de um outro post seu sobre o plugin Extra Checkout. Obrigado!

**Comment by gabriel-americo** [comment]
Ola estou com o mesmo problema do @iCristiano e gostaria de deixar apenas o celular como required, não o telefone, porque pelo pagseguro precisa apenas um numero tanto do celular quanto do telefone,alguém pode me ajudar nessa parte?
