### ISSUE TITLE
Erro ao finalizar pagamento

### ISSUE THREAD

**Issue by GabrielFalkoski** [claudiosanches/woocommerce-pagseguro#46]
Olá,
Estou usando a integração com o método de checkout transparente e, quando finalizo a compra, me retorna a mensagem: "Um erro ocorreu ao processar o seu pagamento, por favor, revise os seus dados e tente novamente. Ou entre em contato conosco para obter assistência.".
Debugando um pouco, vi que o código do erro é "53079", porém esse erro não se encontra nos "erros" do plugin (get_error_message()).
Alguém já passou por algo semelhante?

Desde já, agradeço!

**Comment by claudiosanches** [comment]
Não porque isso não é um erro que seja culpa do usuário ou algo que ele pode alterar.
Esse erro acontece quando o produto não tem nenhum valor.
Algo que por padrão o plugin remove, mas provavelmente esta usando algo personalizado para isso.
Então seria melhor ativar a opção de enviar todos os produtos de uma vez ao contrário de mandar a lista de produtos individuais.
