### ISSUE TITLE
Assumir parcelas com juros

### ISSUE THREAD

**Issue by thiagogsr** [claudiosanches/woocommerce-pagseguro#47]
Opa!

Está implementada a opção de assumir, por exemplo, 3 parcelas sem juros para o comprador, e ele paga o juros da quarta em diante?

**Comment by claudiosanches** [comment]
Da para controlar isso pelo PagSeguro, no painel.
E não tem nenhuma opção para isso hoje na API, pelo menos não que eu consigo encontrar em https://dev.pagseguro.uol.com.br/referencia-da-api/api-de-pagamentos-pagseguro#!/ws_pagseguro_uol_com_br/v2_checkout_xml
