### ISSUE TITLE
Passagem de Dados da Compra

### ISSUE THREAD

**Issue by cabelotaina** [claudiosanches/woocommerce-pagseguro#49]
Olá @claudiosanches,

Estamos precisando de passar parametros de endereço de entrega na compra. O plugin permite fazer isso? Ademais se não permite tem ideia de por onde posso começar para integrar isso no plugin atual?

abs

**Comment by claudiosanches** [comment]
O plugin já passa todos os dados de endereço pro PagSeguro que é necessário pela documentação do PagSeguro.
