### ISSUE TITLE
[Checkout Transparente] Form não inicializa + redirecionamento

### ISSUE THREAD

**Issue by alexandrecanuto** [claudiosanches/woocommerce-pagseguro#50]
Olá, Claudio! @claudiosanches 
Obrigado pelo plugin, sou novo no mundo WordPress + WooCommerce etc e estou com uns probleminhas no checkout transparente com o PagSeguro. Pode me ajudar?

Tentei postar no fórum do WordPress e, sinceramente, não sei se a questão foi ou não. Desculpa se aqui não é o melhor lugar...

1. Na página de checkout, por algum motivo o formulário do plugin PagSeguro (aquele com as opções cartão, transferência, boleto) está escondido na página. O form ( `#pagseguro-payment-form` ) está com `display: none` . Investigando o código do plugin, percebi que a inicialização acontece com o recebimento do evento `updated_checkout`, e debugando o código do checkout do WooCommerce, esse evento é disparado – por algum motivo o código do plugin não está executando após esse evento. Para teste, ao dar um timeout de 10s (por exemplo) no trigger do evento no código do WooCommerce, o formulário do plugin é inicializado e aparece na página corretamente.

2. Selecionando qualquer uma das opções (cartão, transf, boleto) e preenchendo o que tem de ser preenchido, acontece o redirecionamento pra página do PagSeguro Sandbox. Checkout Transparente está selecionado e Extra Checkout Fields esta instalado OK.

Infos adicionais que podem ser úteis:

* Vi que pode ter algo a ver o sessionId estar vazio, mas ele está preenchido. O que parece estar vazio é o `senderTrackingHash=undefined`. Não sei bem o que é isso e se tem alguma relação.

* WooCommerce e WooCommerce PagSeguro atualizados na versão mais recente.

* No status do sistema, tenho dois probleminhas que não consegui resolver e não sei se afetariam:

*Requisição remota do tipo POST:*  `wp_remote_post() falhou. Entre em contato com a sua hospedagem. cURL error 35: Unsupported SSL protocol version`
*Requisição remota do tipo GET:*  `wp_remote_get() falhou. Entre em contato com a sua hospedagem. 200 `

Infelizmente, o cliente não me retornou ainda com autorização de divulgação do link de homologação para postar por aqui. :(

Obrigado pela força, tô ficando careca já. rs

**Comment by alexandrecanuto** [comment]
Envio também o log de uma das tentativas:

```
04-28-2017 @ 14:41:49 - Requesting session ID...
04-28-2017 @ 14:42:01 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 6fadcc8208814d50bf238a0c2526865b
)

04-28-2017 @ 14:42:32 - Requesting token for order 217 with the following data: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<checkout>
  <currency>BRL</currency>
  <reference><![CDATA[WC-217]]></reference>
  <sender>
    <email><![CDATA[c10248781592616627710@sandbox.pagseguro.com.br]]></email>
    <documents>
      <document>
        <type>CPF</type>
        <value>41889699896</value>
      </document>
    </documents>
    <name><![CDATA[Alexandre Almeida]]></name>
  </sender>
  <shipping>
    <type>3</type>
    <address>
      <street><![CDATA[Rua Asdrubal Zanetti]]></street>
      <number>118</number>
      <postalCode>07196210</postalCode>
      <city><![CDATA[Guarulhos]]></city>
      <state>SP</state>
      <country>BRA</country>
    </address>
    <cost>5.00</cost>
  </shipping>
  <items>
    <item>
      <id>1</id>
      <description><![CDATA[Nome do Sneaker - 36]]></description>
      <amount>309.90</amount>
      <quantity>1</quantity>
    </item>
  </items>
  <redirectURL><![CDATA[http://localhost/effex-website/checkout/order-received/217?key=wc_order_590354d878129]]></redirectURL>
  <notificationURL><![CDATA[http://localhost/effex-website/wc-api/WC_PagSeguro_Gateway/]]></notificationURL>
  <maxUses>1</maxUses>
  <maxAge>120</maxAge>
</checkout>

04-28-2017 @ 14:42:42 - PagSeguro Payment Token created with success! The Token is: 9433F98BCECE876004A3CFB80C42C2B4
```

**Comment by claudiosanches** [comment]
O form vai iniciar com JavaScript, o que aparece no console do seu browser?

**Comment by claudiosanches** [comment]
Alias, isso dai é super essencial para o plugin funcionar:

```
Requisição remota do tipo POST: wp_remote_post() falhou. Entre em contato com a sua hospedagem. cURL error 35: Unsupported SSL protocol version
Requisição remota do tipo GET: wp_remote_get() falhou. Entre em contato com a sua hospedagem. 200
```

Precisa entrar em contato com o servidor de hospedagem para resolver isso.
Sem esses dois funcionando o plugin do PagSeguro nunca vai funcionar.
E pelo seu log é do seu ambiente de desenvolvimento e não do site em produção, então não vai ajudar com esta issue.

Enfim, resolva tudo que tem no status do sistema, se tiver ainda problema volte que reabrimos este tópico, obrigado.

**Comment by alexandrecanuto** [comment]
Obrigado pelas dicas, @claudiosanches .

Resolvi os problemas do status do sistema (tinha PHP 7.x e por algum motivo estava aparecendo 5.4 no status, removi versões anteriores do sistema e voilà). Tudo verdinho por lá agora.

Agora já tenho o tal do `sendTrackingHash` também e tudo mais, mas o checkout continua redirecionando, infelizmente.
Sobre o ambiente, sim, está tudo no meu ambiente local – esqueci de mencionar isso. O ambiente de homologação está sem o checkout ainda, estou desenvolvendo local primeiro.

Recebi a autorização sobre homologação, se você puder dar uma olhada: http://staging.effexbrand.com

Um dos produtos liberados pra add no carrinho é http://staging.effexbrand.com/produto/sneakers/perfectto-preto/

E sobre o form, nada aparece no console relacionado ao plugin. Nem erros, nem warning, nem infos (não estou com nenhum filtro ativo).

**Comment by alexandrecanuto** [comment]
(Acabei de subir versão em homologação, está tudo verdinho por lá também.)

**Comment by claudiosanches** [comment]
Problema parece o tema fazendo esse lazy load das coisas.
Além desse lance de carregar o script do PagSeguro no PageSpeed pode ser um dos problemas também.
Melhor abrir exceção pra isso, uma vez que é para pagamento e carrega apenas no checkout.
Sinceramente, seria melhor não habilitar PageSpeed no checkout, porque pode causar mais problemas ainda, além que checkout deve ser uma página sempre fresca.

**Comment by alexandrecanuto** [comment]
Sabe me dizer onde eu habilito / desabilito esse PageSpeed? Até onde eu sei, não tenho isso no projeto... É um plugin? Em staging o cliente instalou outros plugins, mas em local tenho apenas os plugins WooCommerce, WooCommerce PagSeguro, Extra Fields, Ajax Load More e Custom Post Type UI.

Os scripts são carregados normalmente no wp_head, acredito. O carregamento do script do plugin PagSeguro é feito automático, acredito, só instalei o plugin mesmo.

**Comment by claudiosanches** [comment]
Olha o source code ai do link que você mandou, tudo sendo carregado pelo PageSpeed.

![screenshot from 2017-04-28 16-25-01](https://cloud.githubusercontent.com/assets/1264099/25544080/45b0e814-2c2f-11e7-935b-493aea2c33f0.png)

No caso vai ser configuração do servidor isso dai.

Veja a linha juntando todos os scripts em um:

```
<script src="http://staging.effexbrand.com/wp-content,_plugins,_woocommerce-pagseguro,_assets,_js,_frontend,_transparent-checkout.min.js+wp-content,_plugins,_ever-ajax-cart,_js,_add-to-cart-variation.js+wp-includes,_js,_wp-embed.min.js+wp-content,_plugins,_woocommerce,_assets,_js,_jquery-payment,_jquery.payment.min.js+wp-content,_plugins,_woocommerce,_assets,_js,_frontend,_credit-card-form.min.js.pagespeed.jc._AfjDP3seG.js"></script><script>eval(mod_pagespeed_a0I$r7nr10);</script>```

**Comment by alexandrecanuto** [comment]
Pedi ao responsável pelo servidor de homologação para remover o PageSpeed, aparentemente um plugin do Apache onde está instalada a loja.

Desculpe o transtorno, mas se puder dar uma olhada agora @claudiosanches vc poderá salvar vidas rs :)

**Comment by alexandrecanuto** [comment]
Mais infos! O log no PagSeguro parece acontecer sem problemas, inclusive a `<redirectURL>`, mas recebo no site `redirect: https://sandbox.pagseguro...`:

```
HTTP/1.1 POST
/v2/checkout?email=effexbrand@gmail.com&token=05C0A96469564694932B6DE4BFE01B93

host: ws.sandbox.pagseguro.uol.com.br
accept: */*
accept-encoding: deflate, gzip
content-type: application/xml;charset=UTF-8
connection: Keep-Alive
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><checkout>  <currency>BRL</currency>  <reference><![CDATA[EFF-751]]></reference>  <sender>    <email><![CDATA[c10248781592616627710@sandbox.pagseguro.com.br]]></email>    <documents>      <document>        <type>CPF</type>        <value>**omitido**</value>      </document>    </documents>    <name><![CDATA[Alexandre Almeida]]></name>  </sender>  <shipping>    <type>3</type>    <address>      <street><![CDATA[**omitido**]]></street>      <number>118</number>      <postalCode>**omitido**</postalCode>      <city><![CDATA[Guarulhos]]></city>      <state>SP</state>      <country>BRA</country>    </address>    <cost>5.00</cost>  </shipping>  <items>    <item>      <id>1</id>      <description><![CDATA[PERFECTTO - 38]]></description>      <amount>327.41</amount>      <quantity>1</quantity>    </item>  </items>  
<redirectURL><![CDATA[http://staging.effexbrand.com/checkout/order-received/751?key=wc_order_5908b41b5f3d2]]></redirectURL>  <notificationURL><![CDATA[http://staging.effexbrand.com/wc-api/WC_PagSeguro_Gateway/]]></notificationURL>  <maxUses>1</maxUses>  <maxAge>120</maxAge></checkout>

200
Content-Type: application/xml;charset="ISO-8859-1"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><checkout><code>B248FA783838FA59947B1FAD37D92429</code><date>2017-05-02T13:30:29.000-03:00</date></checkout>
```
