### ISSUE TITLE
Valor do pagamento não considera cupons

### ISSUE THREAD

**Issue by thiagogsr** [claudiosanches/woocommerce-pagseguro#51]
Opa

Estou com uma issue onde o valor das parcelas ficam iguais ao valor do produto, sem considerar o cupom aplicado. Isso é alguma configuração do plugin ou bug? Fiz um print para mostrar o problema:

![image](https://cloud.githubusercontent.com/assets/1802025/25831454/98da4c7a-343a-11e7-807d-09e918b227c4.png)

Vou investigar olhando o código também!

**Comment by thiagogsr** [comment]
O cupom é carregado via ajax, mas o input hidden `#pagseguro-cart-total` não é atualizado. Vou tentar implementar esse hook.

**Comment by thiagogsr** [comment]
Aparentemente não é um problema desse plugin, deve ser algo no tema ou no WC. Fechando a issue.

**Comment by thiagogsr** [comment]
Descobri o problema. O WC salva os valores dos inputs antes de substituir o HTML para não perder o que o usuário preencheu, mas esse campo é um input hidden, não há qualquer filtro. Logo esse campo mantém o mesmo valor. Ele faz isso apenas para a forma de pagamento ativa no momento, que no meu caso é cartão de crédito. @claudiosanches a nível de responsabilidade, você acha que esse plugin deveria forçar o update desse campo ou o WC deveria remover os campos input hidden desse "state save"?

**Comment by claudiosanches** [comment]
@thiagogsr preciso testar, mas deveria estar funcionando quando esta verificando o valor ai.

**Comment by thiagogsr** [comment]
@claudiosanches um cenário de teste:

- Chegue no carrinho, selecione cartão de crédito, aplique algum cupom de desconto ou mude a forma de entrega, qualquer coisa que mude o valor.

Problemas:
- Mostra o valor da parcela errada
- Não deixa submeter: dá erro de cartão inválido.

Fiz um teste mudando direto no developer tools e consegui submeter normalmente.

**Comment by claudiosanches** [comment]
@thiagogsr essas coisas antes sempre atualizavam o form de cartão, não estão mais atualizando?

**Comment by thiagogsr** [comment]
@claudiosanches está atualizando o form, mas o woocoomerce tem essa feature que salva em uma variável os valores dos inputs antes, muda o html, depois aplica os valores salvos. Uma forma do usuário não precisar preencher novamente se mudar a forma de entrega, por exemplo.

**Comment by claudiosanches** [comment]
Ahhh, foi atualizado isso no 3.0, vai ser necessário agora forçar atualizar isso, ou pegar por ajax apenas antes de enviar pro gateway

**Comment by thiagogsr** [comment]
Talvez uma solução seja, no Woocommerce, mudar o `val` apenas se o campo estiver em branco, [aqui](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L340-L344).

**Comment by thiagogsr** [comment]
Gosto dessa opção:
> ou pegar por ajax apenas antes de enviar pro gateway

**Comment by thiagogsr** [comment]
@claudiosanches você sabe qual seria essa chamada ajax para pegar o valor? Posso tentar implementar, mas como conheço pouco o WC, não sei a rota para isso.

**Comment by claudiosanches** [comment]
Vai ser necessário criar um endpoint apenas para isso.

**Comment by thiagogsr** [comment]
@claudiosanches será que conseguimos um hotfix nessa parte (podemos fazer esse endpoint em seguida)? ninguém consegue finalizar compra via cartão na minha loja :(

**Comment by claudiosanches** [comment]
O endpoint é o hotfix.

**Comment by claudiosanches** [comment]
@thiagogsr esta é a solução adequada ^
Ainda vai atualizar automaticamente o campo se os dados do cartão estiverem preenchidos, assim o cliente precisa apenas escolher o número de parcelas novamente.

**Comment by thiagogsr** [comment]
Perfeito, vi o commit, parece funcionar bem e menos custoso, valeu pelo tempo

**Comment by claudiosanches** [comment]
Acho que consegue já atualizar para versão 2.12.5.

**Comment by thiagogsr** [comment]
Ainda não chegou no wordpress

![image](https://cloud.githubusercontent.com/assets/1802025/25961115/83fbc056-364f-11e7-8c72-9e01d1d6ad5a.png)

**Comment by claudiosanches** [comment]
Tag foi criada, mas parece que o WordPress esta com delay para criar o novo pacote: https://plugins.trac.wordpress.org/browser/woocommerce-pagseguro/tags/2.12.5

**Comment by thiagogsr** [comment]
Acho que deu algo errado

![image](https://cloud.githubusercontent.com/assets/1802025/25965657/fec24652-365e-11e7-8788-57f14c49b9fc.png)

**Comment by claudiosanches** [comment]
https://make.wordpress.org/plugins/2017/05/11/repository-syncing-issues/

WordPress esta lento com isso hoje.
