### ISSUE TITLE
Parcelas no checkout transparente

### ISSUE THREAD

**Issue by isadorasouza01** [claudiosanches/woocommerce-pagseguro#53]
Olá, sou bastante leiga em programação e nova por aqui, então peço a sua paciência desde já. 🙂

Estou com um problema. Preciso que a opção de parcela 1x esteja sempre selecionada por default e não consigo fazer isso sozinha. Uma outra opção que resolveria a minha vida seria permitir somente a parcela em 1x, eliminando as outras opções. Como faço isso e em qual arquivo eu faço a modificação?

Obrigada por toda a ajuda!

**Comment by claudiosanches** [comment]
Você pode configurar no painel do PagSeguro as parcelas que quer.
Trocar para sempre aparece a primeira parcela é perigoso, uma vez que o cliente pode acabar levando sem estar ciente no numero de parcelas escolhido e acabar precisando reembolsar depois, já vi isso acontecer bastante com outros plugins que tentei fazer isso.

De qualquer forma o que você quer fazer é algo que precisa de programação e algo fora do escopo deste plugin, fica extremamente complicado fazer personalizações para as pessoas, talvez seria melhor você contratar alguém no https://hangarwp.com/
