### ISSUE TITLE
Valor Liquido 

### ISSUE THREAD

**Issue by eldersergio** [claudiosanches/woocommerce-pagseguro#54]
O Woocommerce não me mostra  o valor liquido que já vem do pagserguro                        
ex se uma venda for 100 reais com a taxa do pagseguro ficaria 95.00                        
estou tentando exibir o valor liquido sendo que ele só me retorna o bruto entende

**Comment by claudiosanches** [comment]
Isso é no PagSeguro que você deve fazer, não algo que deveria estar cadastrado no WooCommerce o quanto de taxa você vai pagar no PagSeguro.

**Comment by eldersergio** [comment]
Bom dia Claudio me desculpe, acho que eu não soube me expressar bem, é que no woocommerce ele me retorna apenas o valor bruto da venda, porem eu gostaria de exibir tando o bruto(grossAmout) quanto o liquido(netAmout), já que o pagseguro retorna em xml esses valores.
Já que ele recebe o status da comprar, acredito que ele também pode receber esses dados, desde já eu agradeço.

**Comment by claudiosanches** [comment]
Você consegue usar a API do PagSeguro e pegar o valor que quiser de cada pagamento, tem tudo na documentação deles.

**Comment by eldersergio** [comment]
Desde  já eu agradeço pela a atenção Claudio...
mas o fato é, qual é a url de notificação que o plugin já determina e quais as funções ou arquivo que eu devo modificar para poder exibir oque eu pegar(valor liquido) no woocommerce.
Eu percebi que a url de notificação no pagseguro é https://meusite.com.br/wc-api/WC_PagSeguro_Gateway/, mas eu não encontro essa url em meu ftp, será que esta é a url já determinada pelo o plugin, e se for como eu vou fazer para tratar os xml se ela não existe no meu servidor?
