### ISSUE TITLE
Forçar CEP antes de pedir outros campos do endereço

### ISSUE THREAD

**Issue by miguelurtado** [claudiosanches/woocommerce-pagseguro#56]
Olá Cláudio e pessoal.

No checkout transparente o que acha de esconder alguns campos do endereço até que o cliente digite o CEP. Assim poderia ser mostrado menos campos diminuindo a desistência. A página de finalização do PagSeguro já usa esse recurso.

Posso tentar implementar isso, mas gostaria de uma "luz" da sua parte.

Até mais, Miguel

**Comment by miguelurtado** [comment]
Alias acho que essa implementação seria no https://github.com/claudiosanches/woocommerce-extra-checkout-fields-for-brazil

**Comment by claudiosanches** [comment]
Melhor fazer isso pelo seu tema.

**Comment by miguelurtado** [comment]
Olá Cláudio, obrigado, fiz pelo tema mesmo.

Valeu!
