### ISSUE TITLE
Disparar evento quando ocorrer algum problema durante o checkout transparente

### ISSUE THREAD

**Issue by bruno-rodrigues** [claudiosanches/woocommerce-pagseguro#58]
Boa noite, 

Seria válido a implementação de um evento quando houver algum erro durante o checkout transparente?
Se sim, seria interessante colocá-lo dentro da função `pagSeguroAddErrorMessage` em `transparent-checkout.js`?

**Comment by claudiosanches** [comment]
Mande um Pull Request com isso que podemos implementar.

**Comment by bruno-rodrigues** [comment]
Eu ja fiz num projeto local...

```
		 * Add error message
		 *
		 * @param {string} error
		 */
		function pagSeguroAddErrorMessage( error ) {
			var wrapper = $( '#pagseguro-credit-card-form' );

			$( '.woocommerce-error', wrapper ).remove();
			wrapper.prepend( '<div class="woocommerce-error" style="margin-bottom: 0.5em !important;">' + error + '</div>' );
            $(document).trigger('pagseguro_checkout_has_errors');
		}
```

O que acha dessa solução? a melhor forma de disparar o evento é assim mesmo?

**Comment by bruno-rodrigues** [comment]
Na verdade, o WC já faz isso:
`checkout.js:511`:

    $( document.body ).trigger( 'checkout_error' );

Por isso estou fechando essa issue. Obrigado! =)
