### ISSUE TITLE
Campo de CPF aparecendo 2 vezes no checkout transparente

### ISSUE THREAD

**Issue by nossila** [claudiosanches/woocommerce-pagseguro#59]
Na documentação do plugin diz:

> Para quem estiver utilizando o Checkout Transparente é obrigatório o uso do plugin WooCommerce Extra Checkout Fields for Brazil para enviar o CPF ao PagSeguro, caso o contrário será impossível de finalizar o pedido, veja no guia de instalação como fazer isso.

Porem quando o mesmo esta instalado e devidamente configurado com "Exibir Tipo de Pessoa" como "Pessoa Física apenas" como manda o README o campo de CPF aparece 2 vezes na pagina, uma no formulário de cadastro e outro no formulário de pagamento

Se eu altero as configurações do plugin Extra Checkout Fields for Brazil para não pedir CPF eu sequer consigo terminar a compra porque parece que este plugin do pagseguro esta usando o CPF do Extra Checkout Fields for Brazil, sem ele o CPF vai em branco e a compra não finaliza.

WordPress: 4.8.2
WooCommerce: 3.1.2
WooCommerce Extra Checkout Fields for Brazil: 3.6.0
WooCommerce PagSeguro: 2.12.5

**Comment by claudiosanches** [comment]
> e outro no formulário de pagamento

Sim, é obrigatório por causa do PagSeguro.
Deve ser sempre o CPF do dono do cartão, caso o contrário a compra é negada.
