### ISSUE TITLE
Desconto boleto

### ISSUE THREAD

**Issue by rfbastos** [claudiosanches/woocommerce-pagseguro#61]
Olá Cláudio!

Eu testei seu outro modulo de desconto por metodo de pagamento, mas ele nao atende a minha necessidade de deconto somente para o boleto.

Existe essa possibilidade?

**Comment by claudiosanches** [comment]
O plugin de desconto não vai conseguir aplicar apenas desconto neste plugin.
Talvez em uma versão no futuro quando eu dividir as formas de pagamento em métodos diferentes no PagSeguro.
Além que de qualquer jeito, com o tanto de taxas que o PagSeguro cobra e sendo pago no cartão parcelado você também recebe o dinheiro todo de uma vez, faz com que fique bem complicado dar qualquer desconto para pagamento no PagSeguro.
Seria melhor usar algo para boleto direto ou boleto fora do PagSeguro, pois apenas assim seria vantagem aplicar qualquer desconto.
