### ISSUE TITLE
Status do pedido não altera.

### ISSUE THREAD

**Issue by PabloKamien** [claudiosanches/woocommerce-pagseguro#63]
Olá,

Possuo meu site com este plugin faz mais de ano.

Tive problemas com o meu host, e tive que trocar. Logo após a migração, os status do pedido não está alterando automaticamente, de aguardando para processando. 

Não utilizo Cloudflare, nem nenhuma das ferramentas listadas no FAQ deste plugin.

No site do Pagseguro, consta que está tudo ok.

Qual pode ser o problema?

Obrigado?

**Comment by bruno-rodrigues** [comment]
Seu novo host deve estar bloqueando conexões de entrada, adicione os ips do pagseguro na blacklist do firewall...

**Comment by marcelogarbin** [comment]
Também estou com problemas, resolveu? eu estou utilizando Cloudflare.

**Comment by renanduart3** [comment]
Tbm to com esse mesmo problema. Eu fico na duvida se tem q criar alguma chave de api pra autorizar a alterar os status do pedido no meu servidor. 

*Uso locaWEB

**Comment by claudiosanches** [comment]
Altera sim, se não esta funcionando é por causa do seu servidor, se esta usando locaweb muita coisa já se explica ai. Na FAQ do plugin tem dicas de como resolver isso.
