### ISSUE TITLE
Erro Checkout Transparente

### ISSUE THREAD

**Issue by pandacreative** [claudiosanches/woocommerce-pagseguro#64]
Os clientes informam que acaba travando e não finaliza o pagamento. Segue o erro:

01-11-2018 @ 11:00:16 - PagSeguro payment status for order 9597 is: 4
01-11-2018 @ 12:08:32 - Requesting session ID...
01-11-2018 @ 12:08:33 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => bb37e60f47b3417cbdadded92d75b118
)

01-11-2018 @ 12:09:45 - Requesting session ID...
01-11-2018 @ 12:09:46 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 75e71f17de174e2eb6223890cb55d44a
)

01-11-2018 @ 12:09:54 - Requesting session ID...
01-11-2018 @ 12:09:55 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => f65995ed66eb47a2b66d4d74e39fd441
)

01-11-2018 @ 13:45:19 - Requesting session ID...
01-11-2018 @ 13:45:20 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 7027387abaf249cd8e7364ee8ab6269f
)

01-11-2018 @ 14:38:59 - Requesting session ID...
01-11-2018 @ 14:39:00 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => d1b12b3d416d4cb5a59bdd19ae3df26b
)

01-12-2018 @ 07:26:59 - Requesting session ID...
01-12-2018 @ 07:27:00 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 7f4d7be64a7749ee9745d597d53530e3
)

01-12-2018 @ 08:52:55 - Requesting session ID...
01-12-2018 @ 08:52:57 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => e49b57ee34ca442b9db7f8b1e703eab9
)

01-12-2018 @ 11:24:41 - Requesting session ID...
01-12-2018 @ 11:24:42 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 390f4e97a6c44587af8de00c0c3e6fea
)

01-12-2018 @ 13:34:31 - Requesting session ID...
01-12-2018 @ 13:34:32 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 0235ccfaeb8a4fe58aa55aac8fe120e5
)

01-12-2018 @ 14:22:14 - Requesting session ID...
01-12-2018 @ 14:22:15 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => e3614a95284949579d0703659aa842e3
)

01-12-2018 @ 15:07:24 - Requesting session ID...
01-12-2018 @ 15:07:26 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 5f1ba696352141bc863dd50d0373c757
)

01-12-2018 @ 15:11:39 - Requesting session ID...
01-12-2018 @ 15:11:40 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 17bf03fecb6b45f5ab7f606416634342
)

01-12-2018 @ 15:13:32 - Requesting session ID...
01-12-2018 @ 15:13:33 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 2b597c018d584923b139a9da3469ef11
)

**Comment by pandacreative** [comment]
Para complementar, nem a opção padrão de redirecionamento ta funcionando.

**Comment by pandacreative** [comment]
RESOLVIDO!!! Problema era o LAST_NAME. Ocultei o campo para diminuir a quantidade de campos para o cliente cadastrar e por algum motivo o pagseguro bugou, nunca tinha bugado mas acho que depois da ultima atualização deve ter mudado algo. Enfim, resolvido, ativei de novo o campo e voltou a funcionar tudo.

**Comment by jhoudecarvalho** [comment]
Estou com o mesmo problema, mas ao não preencher o campo, COMPLEMENTOS no checkout passa tranquilo, sabe como posso fazer pra resolver isso?
