### ISSUE TITLE
Woocommerce Subscription

### ISSUE THREAD

**Issue by lupzbr** [claudiosanches/woocommerce-pagseguro#65]
@claudiosanches boa tarde,
Eu estou lendo a documentação do PagSeguro e gostaria de implementar a funcionalidade do plugin para pagamento recorrente.
Gostaria de saber como está o desenvolvimento (se está) para que eu possa ajudar a colocar essa funcionalidade para funcionar.

**Comment by claudiosanches** [comment]
Tentando arrumar tempo para desenvolver isso ainda.
