### ISSUE TITLE
Switch Currency for Woocommerce com PAGSEGURO

### ISSUE THREAD

**Issue by renatoleal-usa** [claudiosanches/woocommerce-pagseguro#66]
Olá!

Tenho uma loja virtual que vende produtos dos Estados Unidos para o Brasil. A moeda está em Dólar (USD) e uso o Switch Currency para fazer a conversão em Reais (BRL). Quando instalo o Plugin do Pagseguro ele me diz que não posso ativar porque a loja está em USD e não BRL.

Vocês teriam alguma solução para isto?

Agradecido,

**Comment by claudiosanches** [comment]
Isso é apenas um alerta, vai funcionar sem problema nenhum quando for para a frente do site e estiver usando reais.
