### ISSUE TITLE
Erro ao finalizar compra: "O Código de checkout não pode mais ser utilizado".

### ISSUE THREAD

**Issue by georgecpacheco** [claudiosanches/woocommerce-pagseguro#67]
Ao finalizar a compra alguns usuários recebem essa mensagem: "O Código de checkout não pode mais ser utilizado". 
Entrei no log do Pagseguro e não tem nada referente a erro. 
O que pode ser?
Desde já, obrigado pela atenção.

**Comment by claudiosanches** [comment]
Código é sempre apenas um por pedido, se não esta funcionando é porque fez teste e esta tentando usar o mesmo código, com o mesmo prefixo e etc.
Por isso o plugin tem opção para mudar o prefixo dos pedidos, já que no PagSeguro não podem repetir.
Já vi isso acontecendo com gente usando em mais de uma loja com o mesmo prefixo.
