### ISSUE TITLE
Clientes não conseguem concluir o pagamento (fica carregando)

### ISSUE THREAD

**Issue by Chicodarave** [claudiosanches/woocommerce-pagseguro#68]
Prezado Claudio, tenho visto vários clientes que tentam efetuar o pagamento pelo PagSeguro e o pedido acaba ficando aguardando ou é cancelado, tem sido um número relativamente alto, porém alguma poucas vezes, a última hoje, o cliente veio me avisar que selecionava o PagSeguro e em alguma das telas ele ficava carregando eternamente e não concluía.
Tem também vários pedidos que concluíram normalmente, então algo está funcionando.
Tentei ligar para o PagSeguro mas não conseguiram ajudar com nada (sabem menos que a gente).
Dai fui olhar o FAQ e consta para desativar "Pagamento via Formulário HTML", e de fato estava ativada (pode ser isso?)
Estou usando o Lightbox.
Venho aqui pedir algum auxílio para resolver isso pois está além do meu conhecimento.
Tem algo que eu possa fazer? Algum teste, alguma informação?
Muito obrigado.

**Comment by Chicodarave** [comment]
Ativei o log e consegui pegar, o cliente fez 3 pedidos sendo que 2 não concluíram.
Como envio o log?

Obrigado novamente.

**Comment by claudiosanches** [comment]
Problema no seu site, da para completar o pedido sem nenhum problema.
Melhor testar com outro tema ou desativando alguns plugins.
