### ISSUE TITLE
Sobre nome do cliente causa erro no checkout

### ISSUE THREAD

**Issue by eduardovaladares** [claudiosanches/woocommerce-pagseguro#70]
Tenho um cliente que relatou por diversas vezes que não conseguia finalizar uma compra, o plugin sempre mandava revisar o cadastro e estava tudo correto, então tive a ideia de reduzir o sobrenome e simplesmente funcionou. Obs: ele possui 7 sobrenomes.

Erro: Um erro ocorreu ao processar o seu pagamento

**Comment by claudiosanches** [comment]
No log do plugin vai mostrar exatamnte qual é o problema para o erro.
