### ISSUE TITLE
Class 'SimpleXMLElement' not found

### ISSUE THREAD

**Issue by jnrbo** [claudiosanches/woocommerce-pagseguro#71]
Após instalar o plugin e clicar em ativar, está aparecendo a seguinte mensagem de erro:

`Fatal error: Class 'SimpleXMLElement' not found in /var/www/html/wp-content/plugins/woocommerce-pagseguro/includes/class-wc-pagseguro-xml.php on line 16`

**Comment by jnrbo** [comment]
Aparentemente no Ubuntu com php7 é preciso instalar:

`apt-get install php7.0-xml`

e depois executar:

`service apache2 restar`

**Comment by claudiosanches** [comment]
Isso geralmente é instalado por padrão junto com o PHP, só não é instalado quando passa flags para o PHP não ativar isso.
