### ISSUE TITLE
Redirecionamento após pagamento

### ISSUE THREAD

**Issue by carlosnpz** [claudiosanches/woocommerce-pagseguro#73]
Gostaria de saber se é possível redirecionar pra outra página, depois que o usuário conclui o pagamento.

**Comment by claudiosanches** [comment]
Já é redirecionado para a página correta do WooCommerce, se mudar essa página vai causar diversos problemas, até mesmo em plugins para mensurar conversões.
Se precisa mostrar algo diferente naquela página, melhor personalizar ela do que direcionar para outra.
