### ISSUE TITLE
Após instalação do plugin o wordpress para de funcionar

### ISSUE THREAD

**Issue by andysteel** [claudiosanches/woocommerce-pagseguro#77]
Estou com um ambiente de teste localhost utilizando o wordpress 4.9.5, woocommerce 3.3.5 e quando instalo o plugin pagseguro (ultima versão 2.12.6) o wordpress para de funcionar, tenho que ir no caminho /wp-content/plugins apagar a pasta do plugin na mão só assim o wordpress volta a funcionar, estou usando o tema Storefront 2.3.1. Poderia me ajudar ?

**Comment by claudiosanches** [comment]
E o que aparece no log de erro do PHP?
Tem certeza que instalou este plugin?
Qual sua versão do PHP?

Vai precisar ativar opção de debug do WordPress para saber exatamente qual é o error, mas pelos meus testes tudo funcionando perfeitamente, além do plugin estar funcionando faz bastante tempo, não recebi qualquer outra mensagem similar a esta, então acredito que deve ser outra coisa além do plugin no seu site.

**Comment by andysteel** [comment]
Ola claudio, minha versão é PHP 7.1.6-2, fiz o debug como você orientou e deu essa mensagem:
[16-May-2018 02:26:41 UTC] PHP Fatal error:  Class 'SimpleXMLElement' not found in /var/www/html/wordpress/wp-content/plugins/woocommerce-pagseguro/includes/class-wc-pagseguro-xml.php on line 16

**Comment by claudiosanches** [comment]
Como explico no plugin, funciona com SimpleXMLElement que vem instalado por padrão no PHP, mas parece que sua instalação fez alguma personalização que removeu isso, então basta instalar no seu servidor.
