### ISSUE TITLE
Após a atualização os pagtos não estão sendo aprovados pela empresa de cartão de crédito

### ISSUE THREAD

**Issue by felipelevangelista** [claudiosanches/woocommerce-pagseguro#78]
Bom dia Claudio,

Tenho usado o seu plugin a pouco mais de um mês e ele tem funcionado perfeitamente e está me ajudando muito. Acontece que desde que eu atualizei para a última versão, eu fiz duas vendas via cartão de crédito e as duas foram canceladas pela empresa de cartão de crédito do meu cliente.

Pode ter alguma coisa a ver com a atualização ou é só uma coincidência?

Obrigado.

**Comment by claudiosanches** [comment]
Não existe qualquer tipo de atualização que eu possa fazer neste plugin e dar problema se a empresa de cartão aceita ou não, isso precisa ser resolvido no PagSeguro.
