### ISSUE TITLE
TLS 1.2 a partir de 30/06/2018

### ISSUE THREAD

**Issue by GricelRio** [claudiosanches/woocommerce-pagseguro#80]
Olá, 
Alguém pode ajudar com esse assunto?
Nossa loja não tem nem SSL, nem TLS 1.2.
Pretendemos colocar, mas nosso provedor (locaweb) só oferece SSL.
Usei o plugin  TLS 1.2 Compatibility Test e o resultado foi que a loja está OK para PayPal e signifca que deve funcionar com outros gateways.
Não consigo contato telefônico com o PagSeguro para suporte e nas comunidades há pouca informação.
Obrigado!

**Comment by claudiosanches** [comment]
Eu não trabalho no PagSeguro, como já digo na descrição deste plugin, ele foi feito sem qualquer ajuda deles.
Sobre o TLS 1.2, quem deve suportar isso é o servidor, se já funciona para o PayPal, vai funcionar para qualquer outra conexão.

**Comment by GricelRio** [comment]
Eu sei, publiquei aqui  porque achei que outras pessoas poderiam ter mais informações.
Obrigada, abraço
