### ISSUE TITLE
Baixa de estoque para pagamentos em boleto

### ISSUE THREAD

**Issue by henrique-rolim** [claudiosanches/woocommerce-pagseguro#82]
Olá.

Gostaria de um Help com relação a baixa dos produtos quando o pagamento é em boleto. O cliente ao pagar via boleto deveria reter o produto para que outros clientes não comprem, para não causar furo nas vendas. Existe alguma possibilidade de solução para isso?

Eu vi que já perguntaram [aqui](https://wordpress.org/support/topic/baixa-de-estoque/#post-10268553) só que não entendi a solução.

**Comment by rangelrmorais** [comment]
Opa, e também não entendi a solução. Mas parece que nem quando o boleto consta como pago no pagseguro, o status no woocommerce é alterado.
