### ISSUE TITLE
nao aparece opçao pagseguro no celular

### ISSUE THREAD

**Issue by hugotau** [claudiosanches/woocommerce-pagseguro#83]
Boas, antes de mais gratidão pelo seu plugin, funcionou muito bem mas tive problemas com o checkout transparente, dava sempre erro nos pagamentos e depois de ativar lightbox nao aparece opçao pagseguro nos celulares...

Tentei varias vezes de varios cels diferentes, aparece opçao no desktop e no cel nao aparece pagseguro...

Troquei pelo plugin do woocommerce para o pagseguro e voltou a aparecer no cel...

Mas prefiro o seu... alguma ideia de como resolver?

Outra coisa vendo serviços e nao preciso de endereços nem nada, quero usar quick checkout for digital goods ou similar onde o cliente apenas coloque nome e email pois ele vai ser redirecionado de qualquer jeito e tem que voltar a preencher os dados pessoais, muito chato e perda de vendas...

Tem como com redirecionamento fazer isso?

Grato.

**Comment by claudiosanches** [comment]
Talvez seja algo no seu site, acabei de fazer testes com um site meu e funcionou sem nenhum problema.
Tente com outro tema, talvez seja erro de JavaScript no seu site também.
