### ISSUE TITLE
Adicionar Taxas Cobradas pelo Pagseguro a Lista de Informações Obtidas

### ISSUE THREAD

**Issue by leandrotavaresrocha** [claudiosanches/woocommerce-pagseguro#84]
Outro dia notei uma informação importante que haviam nos histórico das ordens pagas através do Paypal, mas que não havia no plugin do Pagseguro, a taxa cobrada pelo portal.

Para muitos negócios saber a taxa paga é importante e ter esta informação dentro do wordpress facilita na hora de criar relatórios. Dando uma olhada na API do Pagseguro parece que esta informação existe disponível nos campos intermediationRateAmount e intermediationFeeAmount. Portanto gostaria de saber se uma melhoria dessas é viável? 

Eu considerando contratar um dev para fazer esta melhoria e depois liberar aqui, mas gostaria de saber primeiramente se algo assim é muito complexo?

A documentação da notificação é esta: https://devs.pagseguro.uol.com.br/docs/checkout-web-notificacoes

**Comment by claudiosanches** [comment]
Isso já faz parte dos meus planos para implementar no plugin quando eu tiver tempo livre, se quiser ajudar, fique a vontade.
