### ISSUE TITLE
Total do Checkout Transparente Diferente Devido a Taxas

### ISSUE THREAD

**Issue by leandrotavaresrocha** [claudiosanches/woocommerce-pagseguro#85]
Olá,

Hoje tentei realizar a integração do checkout transparente pela primeira vez e percebi um pequeno problema. Eu utilizo um plugin que adiciona mais R$ 1,00 ao valor total do pedido quando o pagamento for processado por portais de pagamento. Esta taxa (fee) é processada normalmente pelos portais quando utilizando o método de redirecionamento, mas quando tento usar o checkout transparente o total que aparece nas parcelas é diferente do total do pedido. 

Aqui tenho um exemplo do pedido no meu site ainda. Como vocês podem ver o valor está como R$ 4,00: https://drive.google.com/file/d/1GgihCbWkKcJ7XZXZX0LYpg4xs3iOuxCf/view?usp=sharing

Quando sou direcionado para o pagseguro o total continua como R$ 4,00: https://drive.google.com/file/d/1V7aUviGa4McdTpwQaKZywFjJTBbJ47WI/view?usp=sharing

Contudo quando vou verificar o total do pedido que aparece na parcela o valor está sem a taxa de R$ 1,00, ou seja, aparece R$ 3,00: https://drive.google.com/file/d/1PfXpUvSXsHJKOGTJb3xRVnEMQclp2At8/view?usp=sharing

Isto não acontece com outro portais ou com o próprio redirecionamento o que me leva a crer que há algo de diferente no checkout transparente.

Na versão lightbox este problema também não acontece. Aqui tem um exemplo onde o valor de R$ 4,00 se repete: https://drive.google.com/file/d/1qXV0TkD4rYvpwXau7XRd_tNQ8Zb1gfNv/view?usp=sharing

**Comment by claudiosanches** [comment]
> Eu utilizo um plugin que adiciona mais R$ 1,00 ao valor total do pedido quando o pagamento for processado por portais de pagamento. Esta taxa (fee) é processada normalmente pelos portais quando utilizando o método de redirecionamento...

Isso é ilegal no Brasil, mesmo assim tem opção no plugin para enviar o valor total do pedido no lugar de apenas enviar a soma dos items no carrinho, alias, parece que esse plugin esta faezendo alguma gambiarra, porque se estivesse usando `fee` do WooCommerce, já deveria estar somando também.
De qualquer forma tem a opção no plugin que eu falei.

**Comment by leandrotavaresrocha** [comment]
Oi Claudio! Nunca ouvi falar que alterar o preço no Brasil de acordo com o método de pagamento é ilegal, aliás me parece ser justamente o contrário, pois assim dou um desconto para quem está comprando a vista. Agora fiquei curioso com seu ponto, você tem alguma fonte falando sobre isto ser ilegal?

**Comment by claudiosanches** [comment]
Sim, cobrar a mais porque vai passar em cartão ou determinado método é ilegal, não é meu ponto e nem minha opinão, sobre fonte deixo para você pesquisar, problema no plugin eu já falei como arrumar.
