### ISSUE TITLE
variável "settings" não encontrada.

### ISSUE THREAD

**Issue by niltonssjr** [claudiosanches/woocommerce-pagseguro#86]
![erro_pagseguro](https://user-images.githubusercontent.com/25869730/43664735-4b51ccbc-9744-11e8-9ccc-6599255a9d50.jpg)
Cláudio, encontrei um erro ao tentar usar o checkout transparente, dizendo que a variável $settings não existia na linha 134 do class-wc-pagseguro.php. Pelo que vi nas funções acima, não estava sendo carregada a variável com base no get_option. Não sei se a lógica era essa mesma, então deixo como uma sugestão de fix se eu estiver correto.

**Comment by claudiosanches** [comment]
Acabei de corrigir na versão 2.13.1. Obrigado.
